# -*- coding: utf-8 -*-
"""OpenCV_Image_Processing_Techniques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvnoXOifOFXcrhr_vKSfPxeV_i6UGVlX

image augmentation
"""

# pip install opencv-python for jupyter

import cv2

cv2.__version__

img=cv2.imread('/content/download.jpg')
img2=img.copy()

img

from google.colab.patches import cv2_imshow
cv2_imshow(img)

img=cv2.imread('/content/download.jpg',0)# it reduces the rgb
img

# storing image
cv2.imwrite('benzz.jpg',img)

cv2_imshow(img)

#size
print(img.size)

#shape
print(img.shape)

print(type(img)) #type of image

#image slicing
img=img[20:70,100:200]
img

#image rotating
img2=cv2.rotate(img2,cv2.ROTATE_90_CLOCKWISE)

from google.colab.patches import cv2_imshow
cv2_imshow(img2)

img2=cv2.rotate(img2,cv2.ROTATE_180)

from google.colab.patches import cv2_imshow
cv2_imshow(img2)

#image fliping
img2=cv2.flip(img2,1)

from google.colab.patches import cv2_imshow
cv2_imshow(img2)

#resizing
img2=cv2.resize(img,(100,100))

from google.colab.patches import cv2_imshow
cv2_imshow(img2)

#image bluring
img2=cv2.blur(img,(23,50))

from google.colab.patches import cv2_imshow
cv2_imshow(img2)

gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges=cv2.Canny(gray_image,100,200) # Canny is edge reduction
from google.colab.patches import cv2_imshow
cv2_imshow(img)
cv2_imshow(edges)